#!/usr/bin/env python3
"""
Generate OffsetTable.h from eqgame.h, eqmain.h, and eqgraphics.h.

This script parses the offset header files and generates a C++ header that
builds a runtime table of all known offsets for the signature scanner.

Usage:
    python generate_offset_table.py [--eqlib-path PATH]
"""

import re
import os
import sys
import argparse

OFFSET_PATTERN = re.compile(r'#define\s+(\w+_x)\s+(0x[0-9A-Fa-f]+)')

# These defines are not memory addresses - skip them
SKIP_DEFINES = {
    '__ClientDate',
    '__ExpectedVersionDate',
    '__ExpectedVersionTime',
}

HEADER_TEMPLATE = '''/*
 * MacroQuest: The extension platform for EverQuest
 * Copyright (C) 2002-present MacroQuest Authors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#pragma once

// AUTO-GENERATED FILE - Do not edit manually.
// Generated by tools/offsetfinder/generate_offset_table.py

#include <eqlib/Offsets.h>
#include <eqlib/offsets/eqgame.h>
#include <eqlib/offsets/eqmain.h>
#include <eqlib/offsets/eqgraphics.h>

#include <string>
#include <vector>

namespace sigscan {{

enum class OffsetModule
{{
    EQGame,
    EQMain,
    EQGraphics,
}};

struct OffsetInfo
{{
    std::string name;
    uintptr_t preferredAddress;
    OffsetModule module;
}};

#define OFFSET_ENTRY(name, mod) {{ #name, static_cast<uintptr_t>(name##_x), mod }}

inline std::vector<OffsetInfo> GetOffsetTable()
{{
    std::vector<OffsetInfo> table = {{
{entries}
    }};

    return table;
}}

#undef OFFSET_ENTRY

}} // namespace sigscan
'''


def parse_offsets(filepath, module_name):
    """Parse offset defines from a header file."""
    offsets = []
    try:
        with open(filepath, 'r') as f:
            for line in f:
                m = OFFSET_PATTERN.match(line.strip())
                if m:
                    name_with_x = m.group(1)
                    name = name_with_x[:-2]  # strip _x suffix
                    if name not in SKIP_DEFINES:
                        offsets.append((name, module_name))
    except FileNotFoundError:
        print(f"Warning: {filepath} not found", file=sys.stderr)
    return offsets


def main():
    parser = argparse.ArgumentParser(description='Generate OffsetTable.h')
    parser.add_argument('--eqlib-path', default=None,
                        help='Path to eqlib include directory')
    parser.add_argument('--output', default=None,
                        help='Output file path')
    args = parser.parse_args()

    # Find the eqlib path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.normpath(os.path.join(script_dir, '..', '..'))

    if args.eqlib_path:
        eqlib_path = args.eqlib_path
    else:
        eqlib_path = os.path.join(repo_root, 'src', 'eqlib', 'include', 'eqlib', 'offsets')

    # Parse all offset files
    all_offsets = []
    all_offsets.extend(parse_offsets(os.path.join(eqlib_path, 'eqgame.h'), 'EQGame'))
    all_offsets.extend(parse_offsets(os.path.join(eqlib_path, 'eqmain.h'), 'EQMain'))
    all_offsets.extend(parse_offsets(os.path.join(eqlib_path, 'eqgraphics.h'), 'EQGraphics'))

    # Generate entries
    lines = []
    for name, module in all_offsets:
        lines.append(f'        OFFSET_ENTRY({name}, OffsetModule::{module}),')

    entries = '\n'.join(lines)
    output = HEADER_TEMPLATE.format(entries=entries)

    # Write output
    if args.output:
        output_path = args.output
    else:
        output_path = os.path.join(repo_root, 'src', 'plugins', 'sigscan', 'OffsetTable.h')

    with open(output_path, 'w', newline='\n') as f:
        f.write(output)

    print(f"Generated {output_path} with {len(all_offsets)} offset entries")


if __name__ == '__main__':
    main()
